apiVersion: v1
kind: Service
metadata:
  labels:
    app: easytravel-angular
  name: easytravel-angular
  namespace: easytravel
spec:
  ports:
  - name: "frontend"
    port: 80
    targetPort: 8080
  selector:
    app: easytravel-angular
  type: LoadBalancer
